import os
print("API Key loaded:", bool(os.getenv("AIRTABLE_PRODUCTION_API_KEY")))

from honest_logger import log_to_airtable
from function_library import *

# TEMP: manual test
log_to_airtable("Chat Summary Logger", True, "Manual test run passed", "Support")



tests = [
    ("Candidate Screening", function_candidate_screening, "HR"),
    ("Background Check", function_background_check, "HR"),
    ("Reference Verification", function_verify_references, "HR"),
    ("Policy Distribution", function_distribute_policy, "Compliance"),
    ("Onboarding Start", function_start_onboarding, "HR"),
    ("Compliance Training", function_complete_training, "Compliance"),
    ("Safety Monitoring", function_monitor_safety, "Compliance"),
    ("Incident Reporting", function_submit_incident, "Compliance"),
    ("Emergency Trigger", function_trigger_emergency, "Emergency"),
    ("Inventory Sync", function_sync_inventory, "Operations"),
    ("Quote PDF Generator", function_generate_quote_pdf, "Quote Tools"),
    ("Voice Sentiment Logger", function_log_voice_sentiment, "VoiceBot"),
    ("Transcription Storage", function_store_transcription, "VoiceBot"),
    ("Call Quality Analyzer", function_analyze_call_quality, "QA Module"),
    ("Keyword Parser", function_parse_keywords, "NLP"),
    ("Lead Filter", function_filter_leads, "Lead Handling"),
    ("Call Recording Replay", function_replay_call_recording, "VoiceBot"),
    ("Live Transfer", function_trigger_live_transfer, "VoiceBot"),
    ("Sentiment Score Logger", function_log_sentiment_score, "VoiceBot"),
    ("Chat Summary Logger", function_log_chat_summary, "Support"),
    ("File Upload Indexer", function_index_file_upload, "Storage"),
    ("Support Ticket Submission", function_submit_support_ticket, "Support"),
    ("Urgent Ticket Flagger", function_flag_ticket_urgent, "Support"),
    ("Compliance Log Generator", function_generate_compliance_log, "Compliance"),
    ("Rep Performance Scorer", function_score_rep_performance, "QA"),
    ("QA Review Trigger", function_trigger_qa_review, "QA"),
    ("Google Calendar Sync", function_sync_google_calendar, "Scheduling"),
    ("Weekly Digest Sender", function_send_weekly_digest, "Notifications"),
    ("Monthly Metrics Storage", function_store_monthly_metrics, "Analytics"),
    ("Bot Response Tracker", function_track_bot_response, "Botalytics"),
    ("A/B Test Result Storage", function_store_ab_test_result, "Testing"),
    ("Slack Alert Logger", function_push_to_slack_alert_log, "Alerts"),
    ("Internal Compliance Update", function_push_to_internal_compliance, "Compliance"),
    ("Integration Sync Log", function_record_integration_sync, "Integrations"),
    ("File Upload Tracker", function_track_file_upload, "Storage"),
    ("Logger Integrity Flag", function_flag_failed_logger, "Security"),
    ("Command Center Metrics Update", function_update_command_center_metrics, "Command Center"),
    ("Client Communication Tracker", function_track_client_comms, "CRM"),
    ("Contract Upload", function_upload_contract_doc, "Storage"),
    ("QuickBooks Sync", function_sync_quickbooks_invoice, "Accounting"),
    ("Webhook Trigger", function_trigger_external_webhook, "Integrations"),
    ("Bot Custom Personality", function_apply_custom_personality, "VoiceBot"),
    ("Smart Quoting Module", function_run_smart_quote, "Quote Tools"),
    ("Demo Video Logger", function_log_demo_video_play, "Engagement"),
    ("Client Handoff Trigger", function_trigger_client_handoff, "Operations"),
    ("Bot Reset Function", function_reset_bot_state, "VoiceBot"),
    ("AI Suggestion Engine", function_trigger_suggestion_engine, "Command Center"),
    ("Calendar Availability Scan", function_scan_calendar_availability, "Scheduling"),
    ("Auto Follow-Up Reminder", function_trigger_auto_followup, "Notifications"),
    ("Client Feedback Logger", function_log_client_feedback, "Feedback"),
    ("Re-engagement Campaign", function_trigger_reengagement_campaign, "Marketing"),
    ("Project Setup Trigger", function_trigger_project_setup, "Roadmap"),
    ("Data Enrichment Sync", function_sync_data_enrichment, "CRM"),
    ("Secure Vault Update", function_update_secure_vault, "Security"),
    ("Sent Email Tracker", function_log_sent_email, "Outreach"),
    ("AI Training Stats", function_store_ai_training_stats, "AI Dev"),
    ("HubSpot Sync", function_push_to_hubspot, "CRM"),
    ("PDF Quote Email", function_email_pdf_quote, "Quote Tools"),
    ("Client Dashboard Access", function_provision_dashboard_access, "Client Ops"),
    ("Internal SLA Logger", function_log_internal_sla, "Support"),
    ("Performance Issue Flag", function_flag_performance_issues, "QA"),
    ("API Latency Monitor", function_monitor_api_latency, "TechOps"),
    ("Uptime Ping Logger", function_log_uptime_ping, "Monitoring"),
    ("RAG Query Handler", function_handle_rag_query, "Knowledge"),
    ("Billing Profile Sync", function_sync_billing_profile, "Finance"),
    ("Bot Version Logger", function_log_bot_version, "Dev"),
    ("Product Feature Toggle", function_toggle_product_feature, "Dev"),
    ("Live Demo Tracker", function_track_live_demo, "Engagement"),
    ("Tally Form Sync", function_sync_tally_submission, "Forms"),
    ("OCR Extract Trigger", function_trigger_ocr_extract, "Data Intake"),
    ("Security Patch Status", function_log_security_patch_status, "Security"),
    ("API Key Rotator", function_rotate_api_keys, "Security"),
    ("Account Deletion Trigger", function_trigger_account_deletion, "Compliance"),
    ("HIPAA Flag Checker", function_check_hipaa_flags, "Compliance"),
    ("Dynamic Form Logger", function_log_dynamic_form_fields, "Forms"),
    ("Generate Subscription Invoice", function_generate_subscription_invoice, "Billing"),
    ("Compliance Exception", function_record_compliance_exception, "Compliance"),
    ("Trial Expiry", function_notify_trial_expiry, "Sales"),
    ("Sales Call", function_log_sales_call, "Sales"),
    ("Client Review", function_submit_client_review, "Feedback"),
    ("Quarterly Goal", function_notify_quarterly_goal, "Management"),
    ("Feature Announcement", function_push_new_feature_announcement, "Marketing"),
    ("Internal Memo", function_store_internal_memo, "Admin"),
    ("Conversion Risk", function_flag_lead_conversion_risk, "Sales"),
    ("Crisis Mode", function_trigger_crisis_mode, "Command Center"),
    ("QBO Sync Latency", function_log_qbo_sync_latency, "Finance"),
    ("Outreach Script", function_update_outreach_script, "Sales"),
    ("Bot Reset Notify", function_notify_bot_reset, "VoiceBot"),
    ("Bot Training Batch", function_submit_bot_training_batch, "AI"),
    ("Internal Error", function_record_internal_error, "Dev"),
    ("Schema Validation", function_validate_input_schema, "Dev"),
    ("Referral Upload", function_upload_referral_agreement, "CRM"),
    ("Client Data Gap", function_flag_client_data_gap, "Support"),
    ("Slack Summary", function_send_slack_summary, "Notifications"),
    ("Beta Toggle", function_trigger_beta_toggle, "Dev"),
    ("Data Retention Exception", function_log_data_retention_exception, "Legal"),
    ("Google Docs Sync", function_sync_google_drive_docs, "Storage"),
    ("Internal Escalation", function_notify_internal_escalation, "Support"),
    ("Onboarding Milestone", function_track_onboarding_milestone, "HR"),
    ("Credential Invalid", function_flag_invalid_credential, "Security"),
    ("Diagnostic Report", function_generate_diagnostic_report, "QA"),
    ("User Data Export", function_trigger_user_data_export, "Compliance"),
    ("Meeting Minutes", function_log_meeting_minutes, "Support"),
    ("Mismatched Record", function_flag_mismatched_record, "QA"),
    ("Google Sync Confirm", function_confirm_google_sync, "TechOps"),
    ("Overdue Task", function_notify_overdue_task, "Ops"),
    ("Refund Issued", function_log_refund_issued, "Finance"),
    ("AI Training Tag", function_tag_ai_training_entry, "AI"),
    ("Announcement Email", function_push_announcement_email, "Marketing"),
    ("Slack DM", function_log_slack_dm, "Support"),
    ("Payment Error", function_record_payment_error, "Finance"),
    ("Dashboard Refresh", function_trigger_dashboard_refresh, "Reporting"),
    ("Policy Update Notify", function_notify_policy_update, "Compliance"),
    ("Teamwide Notify", function_push_teamwide_notification, "Support"),
    ("VoiceBot Response Gap", function_flag_voicebot_response_gap, "VoiceBot"),
    ("Digital Signature", function_store_digital_signature, "Legal"),
    ("Linked Document", function_log_linked_document, "Storage"),
    ("Bot Shutdown", function_finalize_bot_shutdown, "VoiceBot"),
    ("Internal Transfer", function_record_internal_transfer, "Admin"),
    ("Refund Pending", function_mark_refund_pending, "Finance"),
    ("Sync Verification", function_trigger_sync_verification, "Command Center")
]
run_only_failed = False  # Change to True if retesting failed items
failed_tests = ["AI Suggestion Engine", "Billing Profile Sync"]  # Update manually

for name, fn, module in tests:
    if run_only_failed and name not in failed_tests:
        continue
    try:
        passed = fn()
        log_to_airtable(name, passed, "Function ran successfully", module)
    except Exception as e:
        log_to_airtable(name, False, str(e), module)
        print(f"❌ ERROR: {name} failed with error: {e}")

