services:
  - type: web
    name: icloud-sync
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python sync.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ICLOUD_USERNAME
        sync: false
      - key: ICLOUD_PASSWORD
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_ID
        sync: false
