export const AIRTABLE_BASES = {
  SMARTSPEND_TRACKER_MAIN: {
    baseId: 'appGtcRZU6QJngkQS',
    tables: {
      SMARTSPEND_MASTER_TABLE: 'tbl185XqDi71n76II'
    }
  },
  SMARTSPEND_TRACKER_ARCHIVED_Z: {
    baseId: 'appsViuNPQnXGT82W',
    tables: {
      DASHBOARD_INTAKE_SUBMISSIONS: 'tblWFJVCJIo4yRqVF',
      PHASE_1_LAUNCH_TASKS: 'tblvRrFeKO2gqRBT6',
      YOBOT_INTEGRATION_AND_ROADMAP_TRACKER: 'tblOgmxKHcSDFHX7M',
      SMARTSPEND_MASTER_TABLE_DUPLICATE: 'tbl185XqDi71n76II'
    }
  },
  COMMAND_CENTER_LIVE_OPS: {
    baseId: 'appRt8V3tH4g5Z5if',
    tables: {
      CALL_SENTIMENT_LOG: 'tblfKCV5fE4qdvWu5',
      OPS_METRICS_LOG: 'tbli1OHbGvs4FQ6KP',
      SUPPORT_METRICS_ROLLUP: 'tblrETnBeoUMd71Wx',
      VOICEBOT_SCRIPT_TRACKER: 'tblvDs4fk8r6TTlyL',
      YOBOT_PROMO_CRM_TRACKER: 'tblf0mYX7FYJgwtPe',
      PROJECT_ROADMAP_TRACKER: 'tbl0ZH8s0UoHBvSj2',
      FULL_AUTOMATION_TASK_TEMPLATE: 'tblX2mB0us8P3uZJN',
      TASK_TEMPLATE_TABLE: 'tblakvT7m2dQOjlPC',
      MISSED_CALL_LOG: 'tblFPwk95IFCXX1Ao',
      VOICE_CALL_LOG: 'tblun0fG9zWbsUwC8',
      SLACK_ALERTS_LOG: 'tblXVTyWGrRWnf31H'
    }
  },
  CLIENT_CRM: {
    baseId: 'appMbVQJ0n3nWRl1N',
    tables: {
      SUPPORT_TICKET_SUMMARY: 'tblFTcKVSAAOv5pyQ',
      REP_ASSIGNMENT_TRACKER: 'tblXnxtOUhXNA0ZNq',
      QUOTE_GENERATOR_LOGS: 'tbl7tGwUBXiasxAhj',
      DEAL_MILESTONES_TABLE: 'tbllmq9I7cFU2y7Xz',
      CRM_CONTACTS: 'tblFr3oS4IUFld0d1',
      CLIENT_BOOKINGS: 'tblGu1ieJO1mtYSkb',
      TEAM_MEMBERS: 'tbli9KOJdtoLtrfoX',
      INVOICE_TRACKING: 'tblbOh8Fy1tBKEb5k'
    }
  },
  SALES_AND_AUTOMATION: {
    baseId: 'appe0OSJtB1In1kn5',
    tables: {
      CLIENT_ADD_ON_SELECTIONS_LOG: 'tblfxDj7LdrVNquWG',
      INTERNAL_SECURITY_CHECKLIST: 'tblEtqPDBnZLd0Ubt',
      SLACK_MESSAGE_REVIEW_TRACKER: 'tblj2FzenQSNfu29d',
      CRM_AND_VOICE_AUDIT_LOG: 'tbl0c1WDjkErF2qAI',
      INTEGRATION_SYNC_TRACKER: 'tblF16URVzLZd8QP2',
      INTERNAL_CONFIG: 'tblnGehxqtwpcUanJ',
      FILE_UPLOAD_TRACKER: 'tblphqI0Acsk8BbZG',
      TONE_RESPONSE_VARIANT_LIBRARY: 'tblkIvcuxcZE2IVDF',
      ESCALATION_TRACKER: 'tbl4Qj8m4qlP1ZMHE',
      SYSTEM_ALERTS_LOG: 'tbl9yHYB3peBJBEXD',
      SUPPORT_SETTINGS: 'tblGAlZk8s1bANNSj',
      BOT_HEALTH_MONITOR: 'tbllf2LVhJfNhhBaE',
      BOT_PACKAGES: 'tbl5lPXFQi6jjfHQE',
      YOBOT_PROMPT_LIBRARY: 'tblcNIkQ0HJyVYpVz',
      REP_SCORECARD_LOG: 'tblh3NQUtD22M7tDM',
      BOT_PERSONALITY_PACK_TRACKER: 'tblu1F5YYTmokSpG1',
      NLP_KEYWORD_TRACKER: 'tbl6jk834KPZZJute',
      SUGGESTIONS_PUSH_LOG: 'tblw9PL6VN83ZEDCg',
      ADD_ON_MODULES: 'tbl0AnSPzx37knE2V',
      QA_CALL_REVIEW_LOG: 'tbldfEoTQr2AwZB5m',
      BOTALYTICS_MONTHLY_LOG: 'tblw0LFxyg0CVAgIi',
      FALLBACK_LOG: 'tblvRSWcZyNr8RNfu',
      ADD_ON_BILLING_LINE_ITEMS: 'tblM4VTYU5lWPBgL4',
      AIRTABLE_SCHEMA_DOCUMENTATION: 'tblhL6LEzqGuPjanm',
      PDF_QUOTE_GENERATOR_LOG: 'tblghXq9W9erQ9qIj',
      SALES_ORDERS: 'tblmYdOB13Ze9c4aJ',
      STRIPE_PRICE_TRACKER_LIVE: 'tbl148aRcEy73R7E7',
      FOLLOW_UP_SCHEDULER_LOG: 'tbl1J3AgcA22OIQPP',
      REVENUE_FORECAST_LOG: 'tbl3xRiOhzWXxOuJq',
      VOICEBOT_PERFORMANCE_DASHBOARD_LOG: 'tblNb1Uj2qyUz6v4D',
      CONTRACT_STATUS_TRACKER: 'tbl3Fn7PqK9I9HFBc',
      CLIENT_TOUCHPOINT_LOG: 'tblH2QzeUmvjYqdRI',
      STRIPE_PRODUCTS: 'tblxnajn8WcJoSvvD',
      CLIENT_TIER_VIEW: 'tbl3Ub5y8pI6cYdBb',
      CLIENT_PULSE_TRACKER: 'tbly4pa1fjDBlZqoz',
      LEAD_QUALIFICATION_TRACKER: 'tblLEUH3UophHQLhA',
      COMPLIANCE_CHECKLIST_LOG: 'tblGjGOaQVfsgvBTB',
      FOLLOW_UP_REMINDER_TRACKER: 'tbl0Fya76nVswRpzD',
      COMMAND_CENTER_WIRING_TRACKER: 'tblLpj1543WwwR8m0',
      MANUAL_REVIEW_QUEUE: 'tblUYLcWhVvW7KU3F',
      YOUR_A_B_TEST_LOG: 'tblYqfaqVDjRFQ0Bj',
      VOICE_CALL_LOG: 'tblun0fG9zWbsUwC8',
      MISSED_CALL_LOG: 'tblFPwk95IFCXX1Ao',
      TASK_TEMPLATE_TABLE: 'tblakvT7m2dQOjlPC',
      FULL_AUTOMATION_TASK_TEMPLATE: 'tblX2mB0us8P3uZJN',
      PROJECT_ROADMAP_TRACKER: 'tbl0ZH8s0UoHBvSj2',
      YOBOT_PROMO_CRM_TRACKER: 'tblf0mYX7FYJgwtPe',
      VOICEBOT_SCRIPT_TRACKER: 'tblvDs4fk8r6TTlyL'
    }
  },
  ROI_CALCULATOR: {
    baseId: 'appbFDTqB2WtRNV1H',
    tables: {
      CLIENT_ROI_RESULTS: 'tbl62cLytAMj6rIX6',
      INTEGRATION_TEST_LOG: 'tbl7K5RthCtD69BE1',
      BOTALYTICS_ROI_TRACKER: 'tblt0WJwiw9q9NJoo',
      LOGGER_INTEGRITY_TRACKER: 'tbl4RG0C69J9Mke9s'
    }
  },
  LEAD_ENGINE: {
    baseId: 'appb2f3D77Tc4DWAr',
    tables: {
      CALL_QUEUE: 'tblC9FltlnmzLrSOO',
      SCRAPED_LEADS_UNIVERSAL: 'tbluqrDSomu5UVhDw',
      SCRAPING_CAMPAIGNS: 'tbltGOKyDCoi7JDHb',
      LEAD_SCRAPING_DEMO_LEADS: 'tblmX8bSeeuENtron'
    }
  },
  OPS_AND_ALERTS_LOG: {
    baseId: 'appCoAtCZdARb4AM2',
    tables: {
      SUPPORT_TICKET_LOG: 'tblQPr9cHyNZDpipS',
      SLACK_LOGS: 'tblcFr2l6r9Hgpooz',
      ERROR_AND_FALLBACK_LOG: 'tblo1ESkt9ybkvaJH',
      EVENT_SYNC_LOG: 'tblRfeIho29IKqqCQ',
      INTEGRATION_TEST_LOG_2: 'tblRNjNnaGL5ICIf9'
    }
  }
};
